### ISSUE TITLE
Language Options

### ISSUE THREAD

**Issue by UntotenTheo** [wukko/cobalt#339] opened 2024-01-31 11:41 UTC
**describe the feature you'd like to see**
option to select language please :3

**describe alternatives you've considered**
uhhh none i dont think there are any

**Comment by princessmortix** [comment] 2024-01-31 12:23
Language as page translation, or dubbed audio from youtube?

**Comment by SecularSteve** [comment] 2024-02-08 15:50
> Language as page translation, or dubbed audio from youtube?

I think he means the former.

**Comment by princessmortix** [comment] 2024-02-08 21:27
Dubbed audio is managed by the browser language.

**Comment by wukko** [comment] 2024-02-10 16:59
for dub lang refer to #347

and as for page language, this is a duplicate of #93

**Closed** 2024-02-10 16:59 UTC
Labels: duplicate
