### ISSUE TITLE
Include YouTube Music Thumbnail Support in Metadata

### ISSUE THREAD

**Issue by aymanbest** [wukko/cobalt#240] opened 2023-11-09 20:42 UTC
Hey there! 👋 I hope this finds you well. I've been using your platform and recently encountered a small snag that I believe could enhance the user experience.
It would be fantastic if we could have support for YouTube Music thumbnails in the metadata 
This addition would not only be a great feature for users like myself but could also contribute to the overall improvement of the platform.
I understand there might be other priorities, but whenever there's an opportunity, it would be awesome if the development team could explore this. I'm sure many users, like me, would greatly appreciate it.
Looking forward to the continuous improvement of your platform! 😊🎶

**Comment by wukko** [comment] 2023-11-10 00:11
1. it would be MUCH better if you wrote the issue yourself instead of making chatgpt do it for you
2. this is a duplicate of #72

**Closed** 2023-11-10 00:11 UTC
Labels: duplicate
