### ISSUE TITLE
One specific video failing to download

### ISSUE THREAD

**Issue by SpiritAxolotl** [wukko/cobalt#78] opened 2023-01-29 22:04 UTC
https://youtu.be/JMkrrjKf5AE
this is the link for it. It's just this video. I've tried it multiple times.

**Comment by SpiritAxolotl** [comment] 2023-01-29 22:05
I don't know how to add tags on mobile, sorry

**Comment by wukko** [comment] 2023-01-30 08:26
closing this issue because it's a duplicate of #18. ill make sure to notify people through the web app when videos with content warnings become available for download!

this is why it doesn't work:

![D526F742-03E0-4F01-8747-63057B5AC2B3](https://user-images.githubusercontent.com/71202418/215424749-0c4d31ba-0a70-4ed6-82cd-3e8bd1468398.png)

**Closed by wukko** 2023-01-30 08:26 UTC
Labels: duplicate
