### ISSUE TITLE
Some YouTube videos are impossible to download despite not being age restricted (region lock)

### ISSUE THREAD

**Issue by ElAklamen** [wukko/cobalt#156] opened 2023-07-13 14:44 UTC
It says that some videos i want to download are age restricted. Im sure they are not and i want to know if you can fix it

**Comment by wukko** [comment] 2023-07-21 09:45
some videos are also region restricted, this issue can be addressed only by getting more servers around the world.

i've edited the error message to include info about region restrictions too!

**Comment by wukko** [comment] 2023-07-21 09:52
duplicate of #76

**Closed by wukko** 2023-07-21 09:52 UTC
Labels: duplicate
