### ISSUE TITLE
Youtube downloads 0KB files after recent update

### ISSUE THREAD

**Issue by calebgreski** [wukko/cobalt#187] opened 2023-08-22 03:36 UTC
Downloads from Youtube, using either Auto or Audio modes, results in 0KB files. Tested on two different computers, with multiple different video links, and using the different codec/format options. Was able to successfully download from Twitter and Soundcloud but not Youtube.

Have downloads from late yesterday night (~10pm EST) that downloaded correctly.

I was able to get this error message when trying AV1 encoding.

![image](https://github.com/wukko/cobalt/assets/20373416/8b3b748a-80f4-48f2-b4d5-43bbd1d99c62)

Thank you for this resource, been using it for months now and have appreciated it a lot!

**Comment by wukko** [comment] 2023-08-22 06:39
the issue is now fixed: https://co.wukko.me/ :)

**Closed by wukko** 2023-08-22 06:39 UTC
