### ISSUE TITLE
can't download this public tiktok video? whats happen?

### ISSUE THREAD

**Issue by almafazi** [wukko/cobalt#360] opened 2024-02-16 18:30 UTC
**bug description**
hi, i cant download this tiktok link for no reason, con you explain this?
https://www.tiktok.com/@kevinbadminton/video/7335265467457670405

**reproduction steps**
steps to reproduce the behavior:
1. go to 'cobalt.tools'
2. click on 'search input form' and fill: "https://www.tiktok.com/@kevinbadminton/video/7335265467457670405"
3. download video
4. see error

**screenshots**
<img width="1078" alt="Screenshot 2024-02-17 at 1 30 15 AM" src="https://github.com/wukko/cobalt/assets/18000181/120b6d82-744c-4899-ab36-316cca129fc7">

**links**
cobalt.tools

**platform**
mobile, desktop

**Comment by dumbmoron** [comment] 2024-02-17 21:33
duplicate of #294, moving the repro link there

**Closed by dumbmoron** 2024-02-17 21:33 UTC
Labels: bug
